# Copyright 2023 RealSense, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# DESCRIPTION #
# ----------- #
# Use this launch file to launch multiple devices.
# The Parameters available for definition in the command line for each camera are described in rs_launch.configurable_parameters
# For each device, the parameter name was changed to include an index.
# For example: to set camera_name for device1 set parameter camera_name1.
# command line example:
# ros2 launch realsense2_camera rs_multi_camera_launch.py

"""Launch multiple realsense2_camera nodes."""
import copy
from launch import LaunchDescription, LaunchContext
from launch.actions import OpaqueFunction, LogInfo
from launch.substitutions import LaunchConfiguration
import os
import yaml
import pathlib
import sys
sys.path.append(str(pathlib.Path(__file__).parent.absolute()))
import rs_launch

MULTI_CAMERA_CONFIG_FILE = os.path.join(
    os.path.dirname(__file__), '..', 'config', 'rs_multi_camera.yaml'
)

def yaml_to_dict(path_to_yaml):
    with open(path_to_yaml, "r") as f:
        return yaml.load(f, Loader=yaml.SafeLoader)

def get_camera_configs():
    if not os.path.exists(MULTI_CAMERA_CONFIG_FILE):
        return [{}, {}]

    multi_camera_config = yaml_to_dict(MULTI_CAMERA_CONFIG_FILE)
    cameras = multi_camera_config.get('cameras', []) if multi_camera_config else []

    if isinstance(cameras, dict):
        cameras = [cameras[key] for key in sorted(cameras.keys())]

    cameras = [camera for camera in cameras if isinstance(camera, dict)]
    return cameras if cameras else [{}, {}]

def value_to_launch_default(value):
    if isinstance(value, bool):
        return 'true' if value else 'false'
    return str(value)

def use_lifecycle_node():
    # Load lifecycle nodes setting from YAML dynamically generated by CMAKE instead of environment variable
    lifecycle_param_file = os.path.join(
        os.path.dirname(__file__), '..', 'config', 'global_settings.yaml'
    )
    lifecycle_params = yaml_to_dict(lifecycle_param_file)
    return lifecycle_params.get("use_lifecycle_node", False)

def normalize_serial_no(serial_no):
    if not isinstance(serial_no, str):
        return serial_no

    serial_no = serial_no.strip()
    if len(serial_no) >= 2 and serial_no[0] == serial_no[-1] and serial_no[0] in ["'", '"']:
        serial_no = serial_no[1:-1]
    if serial_no.isdigit():
        serial_no = '_' + serial_no
    return serial_no

def duplicate_params(general_params, suffix):
    local_params = copy.deepcopy(general_params)
    for param in local_params:
        param['original_name'] = param['name']
        param['name'] += suffix
    return local_params

def apply_camera_index_defaults(local_params, index):
    for param in local_params:
        original_name = param.get('original_name', param['name'])
        if original_name in ['camera_name', 'camera_namespace']:
            param['default'] = 'camera' + str(index)

def apply_camera_config_defaults(local_params, camera_config):
    for param in local_params:
        original_name = param.get('original_name', param['name'])
        if original_name not in camera_config:
            continue

        value = camera_config[original_name]
        if original_name == 'serial_no':
            value = normalize_serial_no(value)
        param['default'] = value_to_launch_default(value)

def build_native_params(camera_config):
    # Pass camera config values with their native Python types (bool, int, etc.)
    # directly to the node to avoid the LaunchConfiguration string conversion issue.
    _exclude = {'camera_name', 'camera_namespace', 'serial_no'}
    native = {}
    for k, v in camera_config.items():
        if k in _exclude:
            continue
        native[k] = v
    return native

def set_configurable_parameters(local_params):
    return {
        param['original_name']: LaunchConfiguration(param['name'])
        for param in local_params
    }

def launch_static_transform_publisher_node(context : LaunchContext, camera_configs=None):
    use_lifecycle = use_lifecycle_node()

    log_message = "Launching as LifecycleNode" if use_lifecycle else "Launching as Normal ROS Node"

    # Camera-to-camera extrinsics are provided by charuco_ros2.
    return [LogInfo(msg=f"🚀 {log_message}")]

def generate_launch_description():
    camera_configs = get_camera_configs()
    declarations = []
    launch_actions = []

    for index, camera_config in enumerate(camera_configs, start=1):
        params = duplicate_params(rs_launch.configurable_parameters, str(index))
        apply_camera_index_defaults(params, index)
        apply_camera_config_defaults(params, camera_config)

        declarations += rs_launch.declare_configurable_parameters(params)
        launch_actions.append(
            OpaqueFunction(
                function=rs_launch.launch_setup,
                kwargs={
                    'params': set_configurable_parameters(params),
                    'param_name_suffix': str(index),
                    'native_params': build_native_params(camera_config),
                },
            )
        )

    launch_actions.append(
        OpaqueFunction(function=launch_static_transform_publisher_node,
                       kwargs = {'camera_configs': camera_configs})
    )

    return LaunchDescription(declarations + launch_actions)
